#ifndef XCODEPROJECTMANAGER_GLOBAL_H
#define XCODEPROJECTMANAGER_GLOBAL_H

#include <QtGlobal>

#if defined(XCODEPROJECTMANAGER_LIBRARY)
#  define XCODEPROJECTMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define XCODEPROJECTMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // XCODEPROJECTMANAGER_GLOBAL_H

